### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by skelrilod** [skelrilod/messages-app#1]
- [x] Rename page title to 'message-app'

- [x] Fix search bar 'overflow'

- [x] Add min-height to 'search' bar and 'messages' 
    Messages height still bad

- [ ] Add div search + imgs + max-width 

- [x] Numbers 'message-list-number'

**Comment by skelrilod** [comment]
@matheusagcosta please review this magnificent layout!
